apiVersion: v1
kind: Pod
metadata:
  name: connect-etcd
spec:
  containers:
  - name: connect-etcd
    image: gcr.io/etcd-development/etcd:v3.2.7
    command: [ sh ]
    args: [ "-c", "etcdctl --cacert=/etc/ssl/etcd-connect/etcd-client-ca.crt --cert=/etc/ssl/etcd-connect/etcd-client.crt --key=/etc/ssl/etcd-connect/etcd-client.key --debug=true --endpoints http://10.106.168.16:2379 endpoint status && exec tail -f /dev/null" ]
    env:
    - name: ETCDCTL_API
      value: '3'
    volumeMounts:
    - name: etcd-creds
      mountPath: "/etc/ssl/etcd-connect"
      readOnly: true
  volumes:
  - name: etcd-creds
    secret:
      secretName: etcd-creds
