kind: Service
apiVersion: v1
metadata:
  name: jenkins-service
  labels:
    app.kubernetes.io/name: jenkins-service
spec:
  type: LoadBalancer
  selector:
    app: jenkins-operator
    jenkins-cr: example
  ports:
    - name: http
      port: 8081
      targetPort: 8080
