apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ubuntu-server
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-ubuntu-server
