apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-example1
  name: hello-world1
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-example1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-example1
    spec:
      containers:
      - image: gcr.io/google-samples/node-hello:1.0
        name: hello-world1
        ports:
        - containerPort: 8080
